global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using MoqToNSubstitute.Conversion;
global using MoqToNSubstitute.Extensions;
global using MoqToNSubstitute.Models;
global using MoqToNSubstitute.Templates;
global using MoqToNSubstitute.Tests.Helpers;
global using MoqToNSubstitute.Utilities;
global using NSubstitute;
global using System.Reflection;
